{"uuid": "5f9850ec-2c3a-43db-9d4a-19120b31b55d", "children": ["f957e2c3-9149-4c87-9b9b-e2e394b8efca"], "befores": [{"name": "register_user", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED\n  (Session info: chrome=135.0.7049.85)\nStacktrace:\n\tGetHandleVerifier [0x010780E3+60707]\n\tGetHandleVerifier [0x01078124+60772]\n\t(No symbol) [0x00EA0683]\n\t(No symbol) [0x00E9DAE0]\n\t(No symbol) [0x00E91458]\n\t(No symbol) [0x00E92D40]\n\t(No symbol) [0x00E916E8]\n\t(No symbol) [0x00E91243]\n\t(No symbol) [0x00E90F51]\n\t(No symbol) [0x00E8EF30]\n\t(No symbol) [0x00E8F8CB]\n\t(No symbol) [0x00EA400E]\n\t(No symbol) [0x00F2F427]\n\t(No symbol) [0x00F0D04C]\n\t(No symbol) [0x00F2E824]\n\t(No symbol) [0x00F0CE46]\n\t(No symbol) [0x00EDC5D3]\n\t(No symbol) [0x00EDD424]\n\tGetHandleVerifier [0x012BBBC3+2435075]\n\tGetHandleVerifier [0x012B7163+2416035]\n\tGetHandleVerifier [0x012D350C+2531660]\n\tGetHandleVerifier [0x0108F1B5+155125]\n\tGetHandleVerifier [0x01095B5D+182173]\n\tGetHandleVerifier [0x0107F9B8+91640]\n\tGetHandleVerifier [0x0107FB60+92064]\n\tGetHandleVerifier [0x0106A620+4704]\n\tBaseThreadInitThunk [0x7694FCC9+25]\n\tRtlGetAppContainerNamedObjectPath [0x77CD82AE+286]\n\tRtlGetAppContainerNamedObjectPath [0x77CD827E+238]\n\n", "trace": "  File \"C:\\Users\\Gebruiker\\Documents\\teachMeSkills\\flask\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Gebruiker\\Documents\\teachMeSkills\\flask\\venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Gebruiker\\Documents\\teachMeSkills\\flask\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Gebruiker\\Documents\\teachMeSkills\\flask\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Gebruiker\\Documents\\teachMeSkills\\flask\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Gebruiker\\Documents\\teachMeSkills\\flask\\tests\\ui\\conftest.py\", line 26, in register_user\n    register_page.open_url(f\"{url}register\")\n    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Gebruiker\\Documents\\teachMeSkills\\flask\\tests\\ui\\endpoints\\base_page.py\", line 15, in open_url\n    self.driver.get(url)\n    ~~~~~~~~~~~~~~~^^^^^\n  File \"C:\\Users\\Gebruiker\\Documents\\teachMeSkills\\flask\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 454, in get\n    self.execute(Command.GET, {\"url\": url})\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Gebruiker\\Documents\\teachMeSkills\\flask\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\Gebruiker\\Documents\\teachMeSkills\\flask\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1744713943662, "stop": 1744713948489}], "start": 1744713943662, "stop": 1744713948896}