{"uuid": "922478ce-0c6c-4f1c-902d-be55e4a140e2", "children": ["85dae8ac-5c43-4b12-824e-36db7b74aace"], "befores": [{"name": "register_user", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED\n  (Session info: chrome=135.0.7049.85)\nStacktrace:\n\tGetHandleVerifier [0x010D80E3+60707]\n\tGetHandleVerifier [0x010D8124+60772]\n\t(No symbol) [0x00F00683]\n\t(No symbol) [0x00EFDAE0]\n\t(No symbol) [0x00EF1458]\n\t(No symbol) [0x00EF2D40]\n\t(No symbol) [0x00EF16E8]\n\t(No symbol) [0x00EF1243]\n\t(No symbol) [0x00EF0F51]\n\t(No symbol) [0x00EEEF30]\n\t(No symbol) [0x00EEF8CB]\n\t(No symbol) [0x00F0400E]\n\t(No symbol) [0x00F8F427]\n\t(No symbol) [0x00F6D04C]\n\t(No symbol) [0x00F8E824]\n\t(No symbol) [0x00F6CE46]\n\t(No symbol) [0x00F3C5D3]\n\t(No symbol) [0x00F3D424]\n\tGetHandleVerifier [0x0131BBC3+2435075]\n\tGetHandleVerifier [0x01317163+2416035]\n\tGetHandleVerifier [0x0133350C+2531660]\n\tGetHandleVerifier [0x010EF1B5+155125]\n\tGetHandleVerifier [0x010F5B5D+182173]\n\tGetHandleVerifier [0x010DF9B8+91640]\n\tGetHandleVerifier [0x010DFB60+92064]\n\tGetHandleVerifier [0x010CA620+4704]\n\tBaseThreadInitThunk [0x7694FCC9+25]\n\tRtlGetAppContainerNamedObjectPath [0x77CD82AE+286]\n\tRtlGetAppContainerNamedObjectPath [0x77CD827E+238]\n\n", "trace": "  File \"C:\\Users\\Gebruiker\\Documents\\teachMeSkills\\flask\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Gebruiker\\Documents\\teachMeSkills\\flask\\venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Gebruiker\\Documents\\teachMeSkills\\flask\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Gebruiker\\Documents\\teachMeSkills\\flask\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Gebruiker\\Documents\\teachMeSkills\\flask\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Gebruiker\\Documents\\teachMeSkills\\flask\\tests\\ui\\conftest.py\", line 26, in register_user\n    register_page.open_url(f\"{url}register\")\n    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Gebruiker\\Documents\\teachMeSkills\\flask\\tests\\ui\\endpoints\\base_page.py\", line 15, in open_url\n    self.driver.get(url)\n    ~~~~~~~~~~~~~~~^^^^^\n  File \"C:\\Users\\Gebruiker\\Documents\\teachMeSkills\\flask\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 454, in get\n    self.execute(Command.GET, {\"url\": url})\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Gebruiker\\Documents\\teachMeSkills\\flask\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\Gebruiker\\Documents\\teachMeSkills\\flask\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1744713889593, "stop": 1744713896579}], "start": 1744713889593, "stop": 1744713896951}